# Generated by Django 2.2.5 on 2021-12-06 09:58

import books.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=200, verbose_name='书名')),
                ('Author', models.CharField(default='', max_length=200, verbose_name='作者')),
                ('ISBN', models.CharField(default='', max_length=13, verbose_name='ISBN编号')),
                ('BookCover', models.ImageField(default='static/img/img.jpg', upload_to=books.models.save_image, verbose_name='书籍封面')),
                ('Publish', models.CharField(default='', max_length=200, verbose_name='出版社')),
                ('Description', models.TextField(default='', verbose_name='简介')),
                ('Number', models.IntegerField(default=0, verbose_name='书籍数量')),
            ],
        ),
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('BookId', models.IntegerField(primary_key=True, serialize=False, verbose_name='图书ID')),
                ('UserId', models.IntegerField(verbose_name='使用者id')),
                ('BorrowTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借出时间')),
                ('PredictReturnTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='还书时间')),
                ('Status', models.IntegerField(choices=[(-1, '已超时'), (0, '借出中 '), (1, '已归还')], default=0, verbose_name='状态')),
            ],
        ),
    ]
