# Generated by Django 2.2.5 on 2021-12-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealName',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False, verbose_name='主键玩家id')),
                ('Name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('IdentifyId', models.CharField(max_length=18, verbose_name='身份证号')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tel', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('Account', models.CharField(default='', max_length=18, unique=True, verbose_name='账户')),
                ('UserName', models.CharField(max_length=40, unique=True, verbose_name='用户名')),
                ('Password', models.CharField(max_length=200, verbose_name='MD5加密密码')),
                ('Status', models.SmallIntegerField(default=0, verbose_name='账号状态')),
                ('RealNameAuthentication', models.BooleanField(default=False, verbose_name='实名认证状态')),
            ],
        ),
    ]
